---
# vars file for my_setup
homebrew_pkgs:
  - python@3.9
  - python-tk@3.9
  - python@3.10
  - python-tk@3.10
  - python@3.11
  - python-tk@3.11
  - pyyaml
  - python-tabulate
  - qt
  - pycharm
  - black
  - openjdk@11
  - openjdk@17
  - openssl@3
  - openssl@1.1
  - 1password
  - hashicorp/tap/vault
  - ansible@8
  - ansible-lint
  - ruby
  - wine-stable
  - exiftool
  - bzip2
  - curl
