---
- name: "Check for Homebrew"
  ansible.builtin.stat:
    path: "/opt/homebrew/bin/brew"
  register: home_brew

- name: "Tasks to run when Homebrew is already installed"
  when: not home_brew.stat.exists
  block:
    - name: "Download Homebrew installer"
      ansible.builtin.uri:
        url: https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh
        validate_certs: false
        dest: /tmp/homebrew_install.sh
        mode: a+x

    - name: "Run Homebrew installer"
      ansible.builtin.command:
        cmd: bash -c /tmp/homebrew_install.sh
      environment:
        NONINTERACTIVE: "1"
      register: install_output
      changed_when: install_output.rc != 0
      failed_when: false

    - name: "Command output"
      ansible.builtin.debug:
        var: install_output
      failed_when: install_output.rc != 0

- name: "Update Homebrew"
  community.general.homebrew:
    update_homebrew: true

- name: "Ensure we have tapped all the needed brew taps"
  community.general.homebrew_tap:
    name: "{{ item }}"
    state: present
  loop: "{{ homebrew_taps }}"

- name: "Ensure desired packages are installed at the latest version"
  community.general.homebrew:
    name: "{{ item }}"
    state: latest
  loop: "{{ homebrew_fmls }}"

- name: "Ensure casks are installed"
  community.general.homebrew_cask:
    name: "{{ item }}"
    state: latest
  loop: "{{ homebrew_casks }}"

- name: "Ensure all dependencies are up to date"
  community.general.homebrew:
    upgrade_all: true

- name: "Ensure all dependent casks are up to date"
  community.general.homebrew_cask:
    greedy: true
    upgrade_all: true
