- name: Homebrew setup
  hosts: localhost
  tasks:
  community.general.homebrew:
    update_homebrew: yes

- name: Homebrew package installation
  community.general.homebrew:
    name: "{{ item }}"
    state: latest
  loop:
    - python@3.11
    - python@3.10
    - python@3.9
    - python-tk@3.11
    - python-tk@3.10
    - python-tk@3.9
    - pyyaml
    - python-tabulate
    - qt
    - pycharm
    - openjdk@11
    - openjdk@17
    - openssl@3
    - openssl@1.1
    - 1password
    - hashicorp/tap/vault
    - ansible@8
    - ansible-lint
    - ruby
    - wine-stable
    - exiftool
    - bzip2
    - curl
    
